services:
  checker:
    container_name: bbspriest-checker
    build: .
    ports:
      - 8000:8000
    environment:
      - MONGO_ENABLED=1
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_USER=bbspriest_checker
      - MONGO_PASSWORD=bbspriest_checker
    mem_limit: 1G
    memswap_limit: 2G
    ulimits:
      core:
        soft: 0
        hard: 0
      nproc:
        soft: 4000
        hard: 4000
    depends_on:
      - mongo

  mongo:
    container_name: bbspriest-mongo
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - chaindb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: bbspriest_checker
      MONGO_INITDB_ROOT_PASSWORD: bbspriest_checker
    mem_limit: 1G
    memswap_limit: 2G
    ulimits:
      core:
        soft: 0
        hard: 0
      nproc:
        soft: 4000
        hard: 4000

volumes:
  chaindb:
    name: bbspriest-chaindb
networks:
  default:
    name: bbspriest-checker
