services:
  checker:
    container_name: bbspriest-checker
    build: .
    ports:
      - 8000:8000
    environment:
      - MONGO_ENABLED=1
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_USER=bbspriest_checker
      - MONGO_PASSWORD=bbspriest_checker
    restart: unless-stopped
    depends_on:
      - mongo

  mongo:
    container_name: bbspriest-mongo
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - chaindb:/data/db
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: bbspriest_checker
      MONGO_INITDB_ROOT_PASSWORD: bbspriest_checker

volumes:
  chaindb:
    name: bbspriest-chaindb
networks:
  default:
    name: bbspriest-checker
